// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfMxLbGdfl-l5z6-6vZoCo6QjU0TzhEkE',
    appId: '1:731006899363:web:3759087891573415a7db16',
    messagingSenderId: '731006899363',
    projectId: 'storage-app-a4864',
    authDomain: 'storage-app-a4864.firebaseapp.com',
    storageBucket: 'storage-app-a4864.appspot.com',
    measurementId: 'G-XSR3BGNBEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Y3JLFId9Gc8L74f27UAUVkfztFDWF20',
    appId: '1:731006899363:android:285bdf351dc397f1a7db16',
    messagingSenderId: '731006899363',
    projectId: 'storage-app-a4864',
    storageBucket: 'storage-app-a4864.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtZmM03vtnGFONZiF7OMlZly9gisXtN7w',
    appId: '1:731006899363:ios:1f77a6932d8be81ca7db16',
    messagingSenderId: '731006899363',
    projectId: 'storage-app-a4864',
    storageBucket: 'storage-app-a4864.appspot.com',
    iosBundleId: 'com.chatapp.conversation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtZmM03vtnGFONZiF7OMlZly9gisXtN7w',
    appId: '1:731006899363:ios:995f2a0bd6fcc536a7db16',
    messagingSenderId: '731006899363',
    projectId: 'storage-app-a4864',
    storageBucket: 'storage-app-a4864.appspot.com',
    iosBundleId: 'com.example.chatAppRealtime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfMxLbGdfl-l5z6-6vZoCo6QjU0TzhEkE',
    appId: '1:731006899363:web:63ab860ef0036ea4a7db16',
    messagingSenderId: '731006899363',
    projectId: 'storage-app-a4864',
    authDomain: 'storage-app-a4864.firebaseapp.com',
    storageBucket: 'storage-app-a4864.appspot.com',
    measurementId: 'G-BXLBETVHM0',
  );
}
